name: Release

on: 
  release:
    types: [created]

jobs:
  releases-docker:
    name: Tagged Docker release to Google Artifact Registry
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Get tag
      id: get-tag
      run: echo ::set-output name=release_tag::${GITHUB_REF/refs\/tags\//}
    - id: checkout
      name: Checkout
      uses: actions/checkout@v3

    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        workload_identity_provider: <GCP-WIF>
        service_account: <GCP-SA>
        access_token_lifetime: 600s

    - name: Login to Artifact Registry
      uses: docker/login-action@v2
      with:
        registry: asia-southeast2-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - id: docker-push-tagged
      name: Tag Docker image and push to Google Artifact Registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          <REGISTRY-URL>/go-example:${{ steps.get-tag.outputs.release_tag }}